# PACKAGES

In [1]:
import numpy as np
import pandas as pd

import sys, os
sys.path.append(os.path.abspath("../"))

import utils
from utils.step00_loading import (
    load_jdd_zippe, 
    generate_dataframe,
)
from utils.common.scoring_qualite import (
    compute_quality_score,
    quality_kmeans_category
)
from utils.common.scaler import (
    scale_image_features
)

In [2]:
# CONTEXTE

In [3]:
PREVIOUS_STEP = "jdd"

DATA_JDD = f"/workspace/data/{PREVIOUS_STEP}/ImageAndXML_Data.zip"

STEP = "raw"
PARQUET_IMAGES = f"/workspace/data/{STEP}/ImageAndXML_Data_Images.parquet"
PICKLE_IMAGES = f"/workspace/streamlit/data/{STEP}/ImageAndXML_Data_Images.pkl"

# LOAD IMAGES ORIGINALES

In [4]:
df_images = load_jdd_zippe(DATA_JDD)

IntProgress(value=0, bar_style='info', description='Load images', max=1560, style=ProgressStyle(description_wi…

# Preview DF

In [5]:
df_images.head()

,image_filename,image_type,image_base64
0,0000223278.tif,tif,b'SUkqAHL9AACB/4H/gf+B/4H/h/+B/4H/gf+B/4H/h/+B...
1,0001136521.tif,tif,b'SUkqAAZJAQCBAIEAgQCBANoAAN6f/wAr7QAA3qf/gQCB...
2,0001139626.tif,tif,b'SUkqAKRsAQCBAIEA9QABdEGBAMUAAQtjgQD+AAExRKkA...
3,0001139716.tif,tif,b'SUkqAGCCAQDDAAGfBIEAgQCBAIEAmAAAHrH/wwABKgGB...
4,0001144288.tif,tif,b'SUkqAJjtAACBAIEAgQCBAMIAACSl/wG8C/sAAC6s/4EA...

In [6]:
# DF + FEATURES IMAGE

In [7]:
df_images = generate_dataframe(df_images,STEP)

Préprocessing images (mp, 21 workers): 100%|██████████| 520/520 [01:13<00:00,  7.11it/s]

[generate_dataframe] Temps total : 73.36 s pour 520 images

In [8]:
df_images.head(5)

,_idx,image_filename,image_base64,pipeline_step,sharpness,contrast,brightness,noise,orientation,mirror,density,uniformity,doc_ratio
0,0,0000223278.tif,b'SUkqAHL9AACB/4H/gf+B/4H/h/+B/4H/gf+B/4H/h/+B...,raw,3424.176457,41.334522,0.965340,1.052117,27.367808,0.0,0.038572,1708.542701,NaN
1,1,0001136521.tif,b'SUkqAAZJAQCBAIEAgQCBANoAAN6f/wAr7QAA3qf/gQCB...,raw,4712.027926,85.842642,0.856764,0.917774,38.570160,0.0,0.144089,7368.959171,NaN
2,2,0001139626.tif,b'SUkqAKRsAQCBAIEA9QABdEGBAMUAAQtjgQD+AAExRKkA...,raw,5298.542760,83.196219,0.864653,0.975203,41.655507,0.0,0.136592,6921.610902,NaN
3,3,0001139716.tif,b'SUkqAGCCAQDDAAGfBIEAgQCBAIEAmAAAHrH/wwABKgGB...,raw,5593.623049,83.318549,0.863249,0.977287,44.212102,0.0,0.137633,6941.980554,NaN
4,4,0001144288.tif,b'SUkqAJjtAACBAIEAgQCBAMIAACSl/wG8C/sAAC6s/4EA...,raw,3498.417659,83.921130,0.867103,0.903867,24.769520,0.0,0.133908,7042.756045,NaN

In [9]:
df_images.head(5)

,_idx,image_filename,image_base64,pipeline_step,sharpness,contrast,brightness,noise,orientation,mirror,density,uniformity,doc_ratio
0,0,0000223278.tif,b'SUkqAHL9AACB/4H/gf+B/4H/h/+B/4H/gf+B/4H/h/+B...,raw,3424.176457,41.334522,0.965340,1.052117,27.367808,0.0,0.038572,1708.542701,NaN
1,1,0001136521.tif,b'SUkqAAZJAQCBAIEAgQCBANoAAN6f/wAr7QAA3qf/gQCB...,raw,4712.027926,85.842642,0.856764,0.917774,38.570160,0.0,0.144089,7368.959171,NaN
2,2,0001139626.tif,b'SUkqAKRsAQCBAIEA9QABdEGBAMUAAQtjgQD+AAExRKkA...,raw,5298.542760,83.196219,0.864653,0.975203,41.655507,0.0,0.136592,6921.610902,NaN
3,3,0001139716.tif,b'SUkqAGCCAQDDAAGfBIEAgQCBAIEAmAAAHrH/wwABKgGB...,raw,5593.623049,83.318549,0.863249,0.977287,44.212102,0.0,0.137633,6941.980554,NaN
4,4,0001144288.tif,b'SUkqAJjtAACBAIEAgQCBAMIAACSl/wG8C/sAAC6s/4EA...,raw,3498.417659,83.921130,0.867103,0.903867,24.769520,0.0,0.133908,7042.756045,NaN

# Scale des features

In [10]:
df_images = scale_image_features(df_images)

# DF + QUALITE IMAGE

In [11]:
df_images = compute_quality_score(df_images)

In [12]:
df_images = quality_kmeans_category(df_images)

# SAVE DF -> PARQUET (usage notebook)

In [13]:
df_images.to_parquet(PARQUET_IMAGES, index=False, compression="snappy")

# SAVE DF -> PICKLE (usage streamlit)

In [14]:
df_images.to_pickle(PICKLE_IMAGES)

In [15]:
df_images.head(5)

,_idx,image_filename,image_base64,pipeline_step,sharpness,contrast,brightness,noise,orientation,mirror,density,uniformity,doc_ratio,img_quality_score,quality_category
0,0,0000223278.tif,b'SUkqAHL9AACB/4H/gf+B/4H/h/+B/4H/gf+B/4H/h/+B...,raw,-0.431065,0.045136,0.187014,-0.204282,-0.239628,-0.153695,-0.215047,-0.091485,1.0,0.202664,faible
1,1,0001136521.tif,b'SUkqAAZJAQCBAIEAgQCBANoAAN6f/wAr7QAA3qf/gQCB...,raw,0.094715,3.512549,-3.797060,-0.800277,0.561776,-0.153695,3.478485,4.326778,1.0,0.683973,bonne
2,2,0001139626.tif,b'SUkqAKRsAQCBAIEA9QABdEGBAMUAAQtjgQD+AAExRKkA...,raw,0.334167,3.306379,-3.507594,-0.545499,0.782498,-0.153695,3.216046,3.977598,1.0,0.672598,bonne
3,3,0001139716.tif,b'SUkqAGCCAQDDAAGfBIEAgQCBAIEAmAAAHrH/wwABKgGB...,raw,0.454637,3.315909,-3.559130,-0.536258,0.965394,-0.153695,3.252474,3.993498,1.0,0.685834,bonne
4,4,0001144288.tif,b'SUkqAJjtAACBAIEAgQCBAMIAACSl/wG8C/sAAC6s/4EA...,raw,-0.400755,3.362853,-3.417706,-0.861975,-0.425507,-0.153695,3.122105,4.072159,1.0,0.601794,bonne